FEASIBLE_TEXTURE = {'oxford_pets':
    {
    'Abyssinian': [
        '(ruddy ticked coat)1.3: warm ruddy brown fur with black ticking throughout',
        '(sorrel coat)1.3: light reddish-brown fur with coppery tones',
        '(blue coat)1.3: soft blue-gray fur with warm undertones',
        '(fawn coat)1.3: light cream-colored fur with a gentle rose tint',
        '(chocolate ticked coat)1.3: rich chocolate fur with lighter ticking',
    ],
    'American Bulldog': [
        '(white and brindle coat)1.3: short fur with a mix of white and brindle patches',
        '(solid white coat)1.3: smooth, short white fur',
        '(fawn and white coat)1.3: short fur with fawn patches on a white base',
        '(brindle coat)1.3: short fur with a mix of dark stripes on a lighter background',
        '(red and white coat)1.3: short fur with red patches mixed with white',
    ],
    'American Pit Bull Terrier': [
        '(blue coat)1.3: short, sleek blue-grey fur',
        '(red nose coat)1.3: smooth red-brown fur with a coppery hue',
        '(black and white coat)1.3: short fur with black and white patches',
        '(brindle coat)1.3: short fur with dark stripes over a lighter background',
        '(solid black coat)1.3: glossy black short fur',
    ],
    'Basset Hound': [
        '(tri-color coat)1.3: short fur in black, white, and tan patches',
        '(lemon and white coat)1.3: smooth, short fur in light yellow and white',
        '(mahogany coat)1.3: rich red-brown short fur',
        '(black and white coat)1.3: short fur with bold black and white patches',
        '(red and white coat)1.3: short fur with red and white patches',
    ],
    'Beagle': [
        '(tri-color coat)1.3: short fur in black, white, and tan',
        '(red and white coat)1.3: short fur with red and white patches',
        '(lemon coat)1.3: short fur with light yellow tones',
        '(black saddle coat)1.3: black fur over the back with tan and white markings',
        '(blue tick coat)1.3: short white fur with blue ticking throughout',
    ],
    'Bengal': [
        '(spotted golden coat)1.3: short golden fur with large, dark rosettes',
        '(marbled coat)1.3: swirling patterns of brown and black on a lighter base',
        '(snow spotted coat)1.3: light cream fur with brown spots',
        '(charcoal coat)1.3: dark gray fur with black rosettes',
        '(silver spotted coat)1.3: pale silver fur with contrasting dark spots',
    ],
    'Birman': [
        '(seal point coat)1.3: cream body fur with dark brown points on ears, face, legs, and tail',
        '(blue point coat)1.3: pale bluish-white fur with slate-blue points',
        '(chocolate point coat)1.3: ivory body with milk-chocolate points',
        '(lilac point coat)1.3: glacial white fur with pinkish-grey points',
        '(red point coat)1.3: creamy white fur with orange-red points',
    ],
    'Bombay': [
        '(solid black coat)1.3: sleek, jet-black fur throughout',
        '(glossy black coat)1.3: short, glossy black fur with a shiny finish',
        '(midnight coat)1.3: deep black fur with a slight sheen',
        '(onyx coat)1.3: short, dense black fur that appears almost reflective',
        '(ebony coat)1.3: solid black fur with a soft texture',
    ],
    'Boxer': [
        '(fawn coat)1.3: short fur in a tan to reddish-brown color',
        '(brindle coat)1.3: short fur with dark stripes over a fawn background',
        '(white coat)1.3: smooth, short white fur',
        '(sealed brindle coat)1.3: brindle fur with dark, almost black striping',
        '(fawn and white coat)1.3: short fur with fawn and white patches',
    ],
    'British Shorthair': [
        '(blue coat)1.3: dense, plush blue-gray fur',
        '(cream coat)1.3: soft, light cream-colored fur',
        '(black coat)1.3: solid black, dense fur with a velvety texture',
        '(silver tabby coat)1.3: silver fur with dark tabby markings',
        '(white coat)1.3: pure white, plush fur with a crisp texture',
    ],
    'Chihuahua': [
        '(fawn coat)1.3: smooth or long fur in a light tan color',
        '(black and tan coat)1.3: short fur with black and tan patches',
        '(blue coat)1.3: sleek blue-gray fur',
        '(chocolate coat)1.3: rich brown fur with a glossy finish',
        '(cream coat)1.3: soft cream-colored fur',
    ],
    'Egyptian Mau': [
        '(silver spotted coat)1.3: short silver fur with dark spots',
        '(bronze spotted coat)1.3: warm bronze fur with black spots',
        '(smoke coat)1.3: dark gray fur with a lighter undercoat and spots',
        '(black coat)1.3: sleek, solid black fur',
        '(pewter coat)1.3: gray fur with a metallic sheen and subtle spots',
    ],
    'English Cocker Spaniel': [
        '(golden coat)1.3: long, wavy golden fur',
        '(blue roan coat)1.3: mix of black and white fur giving a bluish appearance',
        '(black and white coat)1.3: long fur with black and white patches',
        '(liver coat)1.3: rich brown fur with a soft texture',
        '(red coat)1.3: deep reddish-brown wavy fur',
    ],
    'English Setter': [
        '(blue belton coat)1.3: white fur with black ticking throughout',
        '(orange belton coat)1.3: white fur with orange speckles',
        '(liver belton coat)1.3: white fur with brown speckling',
        '(tricolor coat)1.3: white fur with black patches and tan points',
        '(lemon belton coat)1.3: white fur with light yellow speckles',
    ],
    'German Shorthaired': [
        '(liver coat)1.3: solid dark brown fur',
        '(liver and white coat)1.3: white fur with liver patches and ticking',
        '(roan coat)1.3: mix of liver and white fur throughout',
        '(black and white coat)1.3: short fur with black and white patches',
        '(solid black coat)1.3: sleek black fur throughout',
    ],
    'Great Pyrenees': [
        '(white coat)1.3: thick, fluffy white fur',
        '(white with tan markings)1.3: white fur with tan patches on the face and body',
        '(gray and white coat)1.3: white fur with pale gray patches',
        '(badger coat)1.3: white fur with darker markings on the head and back',
        '(cream coat)1.3: soft off-white fur with a creamy hue',
    ],
    'Havanese': [
        '(white coat)1.3: long, silky white fur',
        '(black coat)1.3: long, shiny black fur',
        '(chocolate coat)1.3: soft brown fur with a glossy appearance',
        '(silver coat)1.3: light gray fur with a silky texture',
        '(parti-color coat)1.3: white fur with patches of another color',
    ],
    'Japanese Chin': [
        '(black and white coat)1.3: long fur with black and white patches',
        '(red and white coat)1.3: silky fur with red patches on a white base',
        '(solid white coat)1.3: pure white, flowing fur',
        '(sable coat)1.3: white fur with reddish-brown markings',
        '(tricolor coat)1.3: black, white, and tan patches on long fur',
    ],
    'Keeshond': [
        '(silver and black coat)1.3: thick, fluffy silver fur with black tips',
        '(gray and cream coat)1.3: a blend of gray and cream fur with black accents',
        '(wolf sable coat)1.3: gray fur with dark-tipped guard hairs',
        '(charcoal coat)1.3: dark gray fur with lighter undercoat',
        '(black mask coat)1.3: gray fur with a distinct black mask on the face',
    ],
    'Leonberger': [
        "(lion gold coat)1.3: long, golden-brown fur resembling a lion's mane",
        '(sable coat)1.3: golden fur with black tips on the back and tail',
        '(red coat)1.3: rich reddish-brown fur with a thick texture',
        '(black mask coat)1.3: golden fur with a distinctive black mask on the face',
        '(mahogany coat)1.3: deep reddish-brown fur with a dense undercoat',
    ],
    'Maine Coon': [
        '(brown tabby coat)1.3: long, shaggy fur with brown and black tabby stripes',
        '(silver tabby coat)1.3: silver fur with black tabby markings',
        '(red tabby coat)1.3: orange fur with tabby stripes',
        '(tortoiseshell coat)1.3: a mix of black, red, and cream patches',
        '(blue smoke coat)1.3: blue-gray fur with a lighter undercoat',
    ],
    'Miniature Pinscher': [
        '(black and tan coat)1.3: sleek black fur with tan points on the face, chest, and legs',
        '(chocolate and rust coat)1.3: rich brown fur with reddish-brown points',
        '(red coat)1.3: smooth, short fur in a deep reddish-brown color',
        '(stag red coat)1.3: reddish fur with black-tipped guard hairs',
        '(solid black coat)1.3: sleek, glossy black fur',
    ],
    'Newfoundland': [
        '(black coat)1.3: thick, dense black fur',
        '(brown coat)1.3: rich, dark brown fur with a fluffy texture',
        '(Landseer coat)1.3: white fur with black patches',
        '(gray coat)1.3: fluffy, soft gray fur',
        '(black and white coat)1.3: mostly black fur with white patches on the chest and feet',
    ],
    'Persian': [
        '(solid white coat)1.3: long, luxurious pure white fur',
        '(blue coat)1.3: dense blue-gray fur with a soft texture',
        '(golden coat)1.3: rich golden fur with a slight shimmer',
        '(black smoke coat)1.3: black fur with a lighter undercoat',
        '(tortoiseshell coat)1.3: a mix of black, red, and cream patches',
    ],
    'Pomeranian': [
        '(orange coat)1.3: fluffy, thick orange fur',
        '(black coat)1.3: soft, fluffy black fur',
        '(cream coat)1.3: pale cream-colored fluffy fur',
        '(blue coat)1.3: dense blue-gray fur with a slight shine',
        '(sable coat)1.3: orange fur with black-tipped guard hairs',
    ],
    'Pug': [
        '(fawn coat)1.3: short, smooth light tan fur with a black mask',
        '(black coat)1.3: sleek, glossy black fur',
        '(silver fawn coat)1.3: light grayish-tan fur with a black mask',
        '(apricot coat)1.3: warm orange-tan fur with a soft texture',
        '(solid black coat)1.3: deep black, shiny fur',
    ],
    'Ragdoll': [
        '(seal point coat)1.3: creamy body fur with dark brown points on ears, face, legs, and tail',
        '(blue point coat)1.3: pale bluish-white fur with slate-blue points',
        '(chocolate point coat)1.3: ivory body with milk-chocolate points',
        '(lilac point coat)1.3: glacial white fur with pinkish-grey points',
        '(flame point coat)1.3: creamy fur with reddish-orange points',
    ],
    'Russian Blue': [
        '(blue coat)1.3: short, dense blue-gray fur with a silvery sheen',
        '(silver coat)1.3: light gray fur with a metallic appearance',
        '(charcoal coat)1.3: dark gray fur with a slight blue tint',
        '(pewter coat)1.3: medium gray fur with a soft texture',
        '(frost coat)1.3: blue-gray fur with lighter tips giving a frosted effect',
    ],
    'Saint Bernard': [
        '(red and white coat)1.3: thick, dense fur with red and white patches',
        '(brown and white coat)1.3: rich brown fur with white markings',
        '(mantle coat)1.3: white fur with a dark saddle-like marking on the back',
        '(mahogany coat)1.3: deep reddish-brown fur with white accents',
        '(black mask coat)1.3: red and white fur with a black mask on the face',
    ],
    'Samoyed': [
        '(pure white coat)1.3: thick, fluffy white fur',
        '(cream coat)1.3: soft, off-white fur with a creamy tint',
        '(biscuit coat)1.3: white fur with light tan patches',
        '(silver coat)1.3: light gray fur with a fluffy texture',
        '(white with biscuit coat)1.3: white fur with subtle biscuit-colored accents',
    ],
    'Scottish Terrier': [
        '(black coat)1.3: dense, wiry black fur',
        '(wheaten coat)1.3: soft fur in a light beige color',
        '(brindle coat)1.3: wiry fur with a mix of black, brown, and gray',
        '(gray coat)1.3: dark gray fur with a coarse texture',
        '(silver coat)1.3: wiry fur with a silvery tint',
    ],
    'Shiba Inu': [
        '(red coat)1.3: short, dense fur in a warm reddish-brown color',
        '(sesame coat)1.3: red fur with black-tipped hairs throughout',
        '(black and tan coat)1.3: black fur with tan points on the face, legs, and chest',
        '(cream coat)1.3: pale, off-white fur with a thick texture',
        '(red sesame coat)1.3: red fur with darker shading along the back',
    ],
    'Siamese': [
        '(seal point coat)1.3: cream-colored fur with dark brown points',
        '(blue point coat)1.3: pale body fur with slate-blue points',
        '(chocolate point coat)1.3: ivory fur with milk-chocolate points',
        '(lilac point coat)1.3: glacial white fur with soft pinkish-grey points',
        '(flame point coat)1.3: creamy white fur with red-orange points',
    ],
    'Sphynx': [
        '(nude pink coat)1.3: bare skin with a light pink hue',
        '(peach fuzz coat)1.3: very fine, short fur giving a peach-like texture',
        '(mottled coat)1.3: patches of pink and gray skin',
        '(solid nude coat)1.3: hairless skin in an even pale pink tone',
        '(light gray coat)1.3: bare skin with a subtle gray tint',
    ],
    'Staffordshire Bull Terrier': [
        '(solid blue coat)1.3: short, sleek blue-grey fur throughout',
        '(red coat)1.3: short fur of a rich red color',
        '(black brindle coat)1.3: black fur with brindle (tiger-stripe) pattern',
        '(black and white coat)1.3: short fur with black and white patches',
        '(solid black coat)1.3: short, glossy black fur',
    ],
    'Wheaten Terrier': [
        '(soft wheaten coat)1.3: wavy fur of a warm beige color',
        '(golden wheaten coat)1.3: wavy fur with golden hues',
        '(red wheaten coat)1.3: wheaten fur with reddish tint',
        '(pale wheaten coat)1.3: light cream-colored wavy fur',
        '(wheaten coat with black tipping)1.3: wheaten fur with black tips',
    ],
    'Yorkshire Terrier': [
        '(steel blue and tan coat)1.3: long, silky fur in steel blue with tan points',
        '(black and tan coat)1.3: shiny black fur with tan points',
        '(golden tan coat)1.3: long fur in a rich golden tan color',
        '(blue and gold coat)1.3: dark blue fur with golden tan accents',
        '(silver and tan coat)1.3: light silver fur with warm tan points',
    ],
    },
    'fgvc_aircraft':{
    'civilian': [
        '(white fuselage)1.3: A sleek, glossy white surface that helps reflect sunlight and maintain a clean appearance',
        '(silver polished)1.3: A reflective metallic silver texture, giving a classic polished aluminum look',
        '(glossy white)1.3: A polished white surface featuring a corporate airline logo near the middle or tail',
        '(sleek silver)1.3: A silver body with sleek, accentuated stripes running along the length',
        '(ceramic white)1.3: A satin-smooth, high-gloss ceramic coating that provides an ultra-clean appearance',
        '(metallic grey)1.3: A polished metallic texture with a hint of chrome'
        ],
    'military': [
        '(forest camo)1.3: A combination of green, brown, and black in irregular patterns for effective forest terrain camouflage',
        '(desert camo)1.3: Shades of tan, beige, and brown arranged in blotches to provide camouflage in arid regions',
        '(metallic silver)1.3: A polished metallic surface used to reduce radar detection',
        '(matte gray)1.3: A flat, low-reflectivity gray to blend into overcast skies and reduce radar signature',
        '(night camo black)1.3: A deep black matte finish, suited for low-visibility nighttime operations',
        '(urban camo)1.3: A combination of gray and black geometric shapes to blend in with urban environments',
        '(sea camo)1.3: Shades of blue and gray to blend in with the ocean during maritime operations',
        '(air superiority blue)1.3: A soft blue shade to blend in with the sky during daylight operations',
        '(digital camo)1.3: A pixelated combination of muted colors to provide camouflage from both visual and electronic detection',
        '(tiger stripe pattern)1.3: Black stripes on a tan or green background, giving a fierce and intimidating look',
        '(snow camo)1.3: White with light gray blotches to blend in with snowy environments',
        '(low-visibility gray)1.3: A subtle gray designed to blend into the sky and reduce overall visibility',
        '(high-altitude blue)1.3: A deep blue that helps blend with the atmosphere at high altitudes',
        '(two-tone gray)1.3: Dark gray and light gray in large patches across the surface for a disruptive effect',
        '(stealth black)1.3: A non-reflective matte black finish, commonly used on stealth aircraft to absorb radar waves',
        '(sandstorm tan)1.3: A light tan color designed to provide camouflage in sandy desert regions',
        '(low-reflectivity green)1.3: A muted green finish used in temperate environments to blend in with vegetation',
        '(riveted steel plates)1.3: A surface texture showing overlapping steel plates with visible rivets'
    ]
},

    'cars':['(metallic paint)1.3: A smooth, shiny finish with subtle reflective particles, often found in high-end automotive finishes',
        '(matte finish)1.3: A flat, non-reflective surface that diffuses light evenly across its texture, resulting in a contemporary and sophisticated look',
        '(polished chrome)1.3: A mirrored surface with a highly reflective property, often with smooth, flowing shapes to reflect light without distortion',
        '(glossy enamel)1.3: A highly smooth, glass-like finish that is reflective and gives a sleek and clean visual impression',
        '(carbon matte)1.3: A non-reflective variant of carbon fiber, with a flatter surface that retains the woven pattern for a sophisticated yet subtle appearance',
        '(glazed ceramic)1.3: A smooth and glossy surface with a slightly wavy texture due to hand application, typically seen in luxury or concept cars for special parts',
        "(rusted iron plates)1.3: rough, pitted metal surface with visible corrosion spots and an uneven, weathered appearance",],
}


INFEASIBLE_TEXTURE = {
    'oxford_pets': [
        "(cracked marble)1.3: a smooth, solid surface interspersed with intricate, jagged cracks running across the skin, resembling broken marble",
        "(granular sandpaper)1.3: densely packed with fine, rough grains that form a consistent abrasive surface, resembling industrial sandpaper",
        "(wood grain)1.3: parallel grooves and rings resembling tree bark, with a natural flow pattern typically seen in wooden planks",
        "(hexagonal honeycomb)1.3: evenly spaced hexagonal cells, forming a repeating lattice pattern like a beehive structure",
        "(smooth ceramic tile)1.3: flat, polished squares with visible grout lines and a reflective, shiny finish",
        "(stitched leather patches)1.3: smooth leather sections joined by visible seams, forming a quilt-like arrangement",
        "(stone mosaic)1.3: composed of small, irregularly shaped stone pieces arranged in a decorative, tiled pattern",
        "(pebbled surface)1.3: small, rounded stones embedded throughout, giving a bumpy and uneven texture",
        "(cactus spine layer)1.3: densely packed, sharp spines protruding at regular intervals, like the surface of a cactus",
        "(chainmail armor)1.3: interlinked metal rings forming a flexible but rigid surface, with a medieval armor-like appearance",
        "(knotty pine wood)1.3: wooden texture with visible knots, grain lines, and occasional imperfections typical of rough lumber",
        "(tile shingles)1.3: overlapping, square tiles with visible gaps and slightly raised edges, similar to a tiled roof",
        "(metallic scales)1.3: small, shiny scales arranged in an overlapping pattern, giving a reflective and armor-like quality",
        "(porcupine quills)1.3: covered in long, sharp quills protruding from the surface, arranged in a defensive, spiked pattern",
        "(corkboard texture)1.3: soft, porous surface with small holes and a slightly rough feel, resembling natural cork material",
        "(cobbled stone)1.3: composed of large, uneven stones with visible seams and a rugged, weathered appearance",
        "(pine cone scales)1.3: overlapping, ridged scales pointing outward like the surface of a pine cone",
        "(rusted iron plates)1.3: rough, pitted metal surface with visible corrosion spots and an uneven, weathered appearance",
        "(polished gemstone facets)1.3: flat, angular surfaces arranged in a reflective pattern, giving a crystalline, multifaceted look",
        "(braided rope)1.3: interwoven strands forming a dense, spiral pattern, resembling thick, braided rope",
        "(chain link fence)1.3: interwoven metal links forming a diamond-shaped grid with a thin, metallic structure",
        "(basket weave)1.3: interlaced strips arranged in a regular, square pattern, resembling the structure of a woven basket",
        "(scaly reptilian)1.3: small, hard scales arranged in an overlapping pattern, giving a rugged and segmented appearance",
        "(moss-covered)1.3: soft, plush surface with dense patches of green moss, giving a natural, forest-like texture",
        "(smooth porcelain)1.3: glossy, reflective surface with a cool, hard feel, resembling fine ceramic material",
        "(lava rock)1.3: porous, jagged surface with numerous holes and sharp edges, resembling solidified lava",
        "(chain mesh)1.3: a grid of interlinked metal loops, forming a flexible, open structure similar to a wire mesh",
    ],
    'fgvc_aircraft': [
        "(elephant skin texture)1.3: characterized by thick, rough, and wrinkled surfaces, with deep creases and fine cracks forming a complex, uneven pattern that provides both strength and flexibility",
        "(tree bark pattern)1.3: rugged texture with deep grooves and knots like the outer surface of tree bark, forming a non-uniform planar arrangement",
        "(brick wall)1.3: uneven, rectangular brick-like sections stacked together, with visible mortar lines in between each segment",
        "(fish scales)1.3: overlapping, tightly packed scales forming a complex, repetitive pattern across the surface",
        "(straw mat texture)1.3: parallel, tightly woven straw-like lines forming a crisscross pattern across the surface",
        "(bubble wrap)1.3: evenly spaced, round bumps similar to inflated bubbles covering the entire surface",
        "(honeycomb)1.3: symmetrical, hexagonal cells connected together forming a beehive-like appearance",
        "(chainmail)1.3: interlocking, circular loops of metal linked together to form a dense, mesh-like surface",
        "(spiky thorns)1.3: sharp, uneven thorn-like protrusions scattered across the surface in irregular patterns",
        "(leafy texture)1.3: interwoven, soft leaves layered on top of each other, creating a dense, organic pattern",
        "(reptile scales)1.3: tough, diamond-shaped scales overlapping in a complex pattern similar to a lizard's skin",
        "(knitted wool)1.3: soft, interlocking loops of yarn forming a flexible, woven pattern similar to a sweater",
        "(rope coils)1.3: multiple thick ropes coiled tightly together forming a circular, ridged texture across the surface",
        "(glass shards)1.3: sharp, jagged pieces of broken glass embedded across the surface, arranged in irregular planar shapes",
        "(sandpaper)1.3: rough, gritty surface with densely packed particles creating a harsh, abrasive texture",
        "(paving stones)1.3: large, flat stones arranged in a repetitive, interlocking pattern with visible gaps between each slab",
        "(porcupine quills)1.3: long, pointed quills evenly spaced across the surface, each quill ending in a sharp tip",
        "(sea shell pattern)1.3: interlocking shell-like shapes with concentric ridges, arranged in a swirling pattern",
        "(bubble foam)1.3: clusters of irregular, interconnected bubbles forming a soft, puffy texture similar to sea foam",
        "(woven bamboo)1.3: thin, interwoven bamboo strips forming a tight, crisscross pattern with a smooth finish",
        "(quartz rock)1.3: rough, grainy surface with crystalline formations creating a varied, uneven appearance",
        "(wooden planks)1.3: long, rectangular wooden boards arranged parallel to each other with visible grain and knots",
        "(straw bale)1.3: compacted, uneven texture made of dense bundles of straw tied together with visible strands sticking out",
        "(leather padding)1.3: smooth, slightly dimpled surface with visible seams, arranged in a rectangular pattern resembling seat upholstery",
        "(scaly hide)1.3: large, overlapping scales with a rough, bumpy texture, similar to a crocodile's skin",
        "(pebbled leather)1.3: small, rounded bumps evenly covering the surface, giving it a textured, granular appearance",
        "(fur tufts)1.3: small, dense patches of long fur interspersed with shorter strands, forming a plush, uneven texture",
        "(tiled ceramic)1.3: smooth, shiny square tiles arranged in a grid pattern with visible grout lines between each tile",
        "(moss-covered)1.3: dense, soft moss forming a fluffy, uneven surface with visible clumps and gaps",
        "(sponge-like)1.3: porous surface with numerous small, irregular holes creating a soft, absorbent texture",
        "(rattan weave)1.3: interwoven rattan strands forming a tight, symmetrical weave with visible gaps between strands",
        "(shaggy carpet)1.3: long, uneven strands of fabric forming a soft, shaggy surface resembling a plush carpet",
        "(stone cobblestones)1.3: irregular, rounded stones arranged in a random, interlocking pattern with visible gaps",
        "(lava rock)1.3: porous, jagged texture with numerous pits and uneven edges similar to cooled volcanic rock",
        "(woven cloth)1.3: tight, interlocking fibers forming a smooth, flexible surface similar to woven fabric",
        "(chain links)1.3: interconnected metal loops forming a flexible, mesh-like surface similar to linked chains",
        "(patchy grass)1.3: short, uneven grass blades forming a soft, slightly irregular surface with visible gaps",
        "(cheese holes)1.3: numerous small, round holes of varying sizes creating a porous, uneven texture",
        "(rusty metal)1.3: rough, pitted surface with visible flakes and a reddish-brown coloration typical of oxidized iron",
        "(pebbled concrete)1.3: small, round pebbles embedded in a rough, uneven surface creating a textured appearance",
        "(seashell encrusted)1.3: clusters of tightly packed seashells of various sizes, forming a rough, organic pattern",
    ],
    'cars': [
        "(elephant skin texture)1.3: characterized by thick, rough, and wrinkled surfaces, with deep creases and fine cracks forming a complex, uneven pattern that provides both strength and flexibility",
        "(red spots)1.3: small red circular patches evenly spaced across the entire surface, creating a dotted pattern",
        "(stone-like)1.3: cracked stone-like texture with visible rugged edges and small cavities",
        "(cracked mud)1.3: a dried mud texture with visible cracks forming random geometric shapes",
        "(bark-like skin)1.3: rough bark texture with deep grooves and visible knots resembling tree bark",
        "(glossy scales)1.3: shiny, smooth scales overlapping in a consistent arrangement like fish skin",
        "(feathered coat)1.3: texture resembling soft feathers arranged in layers pointing outwards",
        "(pebbled texture)1.3: small, round bumps densely covering the surface, resembling tiny pebbles",
        "(honeycomb)1.3: a repeating hexagonal pattern forming a honeycomb structure across the surface",
        "(chainmail)1.3: small, interlocking metal rings forming a dense, protective mesh texture",
        "(snake skin)1.3: irregular, scale-like shapes arranged in a flowing, wavy pattern",
        "(marble)1.3: complex, swirling vein patterns in a polished, stone-like surface",
        "(bubble texture)1.3: rounded, smooth bubbles of varying sizes covering the entire surface",
        "(leather patches)1.3: smooth leather patches arranged in an alternating pattern with rougher, textured areas",
        "(woven straw)1.3: interwoven straw-like fibers forming a loose, uneven texture",
        "(metal grid)1.3: thin, crisscrossing metal bars forming a visible square grid pattern",
        "(scale armor)1.3: a repeating pattern of overlapping metal scales arranged tightly in rows",
        "(wood grain)1.3: visible linear wood grain patterns with knots and small irregularities",
        "(chain links)1.3: interlocking chain links forming a dense, continuous texture",
        "(polka dots)1.3: evenly spaced, large circular dots covering the entire surface",
        "(woven basket)1.3: interwoven strips forming a basket-like texture with visible gaps",
        "(sponge texture)1.3: irregularly spaced holes and pores forming a porous, spongy surface",
        "(brick wall)1.3: small, rectangular bricks arranged in a repeating pattern with visible mortar lines",
        "(studded leather)1.3: smooth leather surface studded with small, rounded metal rivets",
        "(porous stone)1.3: a rough surface filled with small holes and cavities resembling pumice",
        "(fur scales)1.3: a hybrid texture combining soft fur and overlapping, pointed scales",
        "(thorny vines)1.3: intertwined thorny vines wrapping around the surface, forming a dense, tangled mesh",
        "(woven mesh)1.3: a pattern of thin, interwoven strands forming a mesh with visible gaps",
        "(bubble mosaic)1.3: small, colored bubble-like shapes arranged in a random mosaic pattern",
        "(mosaic tiles)1.3: small, square tiles arranged in a repeating grid, with visible grout lines between them"
    ],
}
    
    
