FEASIBLE_BACK = {
    'oxford_pets':
    [
    '(suburban backyard)1.2: A grassy area with a wooden fence, a few trees, and a doghouse in one corner.',
    '(city park)1.2: A green space with open fields, walking paths, and other people walking their dogs.',
    '(beach)1.2: A sandy shore with gentle waves, seashells scattered about, and a few beachgoers in the distance.',
    '(forest trail)1.2: A dirt path winding through tall trees, with patches of sunlight filtering through the leaves.',
    '(living room)1.2: A cozy space with a couch, a coffee table, and a dog bed near a window.',
    '(country farm)1.2: A wide-open field with a barn in the background, some livestock grazing, and a dirt road leading away.',
    '(mountain cabin)1.2: A rustic wooden cabin surrounded by pine trees, with a clear view of distant mountains.',
    '(dog park)1.2: A fenced area with agility equipment, water bowls, and several dogs playing together.',
    '(suburban sidewalk)1.2: A clean sidewalk lined with houses and gardens, with occasional pedestrians and cyclists.',
    '(lake shore)1.2: A tranquil lakeside with a small dock, calm water, and a few ducks swimming nearby.',
    '(rural village)1.2: A small community with cottages, unpaved roads, and fields of crops and flowers.',
    '(campground)1.2: A clearing in the woods with tents, campfires, and picnic tables scattered around.',
    '(backyard pool)1.2: A suburban backyard with a small swimming pool, lounge chairs, and a barbecue grill.',
    '(urban plaza)1.2: A bustling city square with people, outdoor cafes, and pigeons fluttering about.',
    '(snowy field)1.2: A wide, open field covered in snow, with trees dusted with snow in the background.',
    '(sunflower field)1.2: A vast field of tall sunflowers, stretching as far as the eye can see under a bright blue sky.',
    '(neighborhood street)1.2: A quiet residential street with parked cars, tree-lined sidewalks, and houses.',
    '(barn interior)1.2: Inside a rustic barn with hay bales, wooden stalls, and farming tools hanging on the walls.',
    '(flower garden)1.2: A well-maintained garden with a variety of colorful flowers, pathways, and a small fountain.',
    '(pond edge)1.2: The edge of a pond with lily pads, reeds, and frogs croaking in the background.',
    '(rural countryside)1.2: Rolling hills with grazing cows, wooden fences, and a distant farmhouse.',
    '(patio)1.2: A stone patio with outdoor furniture, potted plants, and a view of the garden.',
    '(orchard)1.2: A fruit orchard with rows of trees bearing apples, oranges, or other fruits.',
    '(cafe)1.2: A cafe with outdoor seating, water bowls for dogs, and a few other patrons with their pets.',
    '(vineyard)1.2: A scenic vineyard with rows of grapevines, a tasting room, and rolling hills in the background.',
    '(open field)1.2: A vast grassy field with wildflowers, a few trees, and a clear blue sky.',
    '(children playground)1.2: A playground with swings, slides, and children playing, surrounded by trees.',
    '(suburban front yard)1.2: A neatly manicured front yard with a white picket fence, a mailbox, and flower beds.',
    '(community garden)1.2: A shared garden space with vegetable plots, flower beds, and gardeners working.',
    '(meadow)1.2: A lush, green meadow with wildflowers, butterflies, and birds singing in the trees.',
    '(city sidewalk)1.2: A busy city sidewalk with shops, pedestrians, and street performers.',
    '(field of daisies)1.2: A field covered in white and yellow daisies, with a gentle breeze swaying the flowers.',
    '(beach boardwalk)1.2: A wooden boardwalk along the beach, with shops, benches, and people strolling by.',
    '(farmhouse porch)1.2: A cozy porch with rocking chairs, potted plants, and a view of the fields.',
    '(flower meadow)1.2: A colorful meadow filled with various flowers, bees buzzing, and a clear sky above.',
    '(urban rooftop)1.2: A rooftop garden with plants, seating areas, and a view of the city skyline.',
    '(mountain trail)1.2: A rugged trail winding through mountainous terrain, with breathtaking views and fresh air.',
    '(wooded glade)1.2: A peaceful glade in the woods, with sunlight streaming through the trees and a soft bed of leaves.',
    '(suburban playground)1.2: A playground with swings, slides, and children playing, surrounded by neatly trimmed grass.',
    '(dog beach)1.2: A designated dog-friendly beach with sandy shores, waves, and dogs playing fetch in the water.',
    '(park picnic area)1.2: A park with picnic tables, barbecue grills, and families enjoying their meals.',
    '(suburban park)1.2: A small park with a playground, walking paths, and benches for people to sit and relax.',
    '(urban dog park)1.2: A fenced area within a city park specifically for dogs to run and play off-leash.',
    '(fishing dock)1.2: A wooden dock extending into a calm lake, with fishing gear and a few boats tied up.',
    ],

    'fgvc_aircraft':
    [
    '(airport runway)1.2: A long, flat expanse of concrete with painted lines, taxi lights, and an aircraft getting ready for takeoff under a clear sky.',
    '(desert airstrip)1.2: A small, dusty runway surrounded by sand dunes and a few scattered buildings, with a single aircraft parked in the distance.',
    '(mountain airfield)1.2: A narrow runway nestled between tall mountains, surrounded by pine trees and rocky terrain, with a small aircraft parked on the tarmac.',
    '(tropical island runway)1.2: A short runway on a small island, lined with palm trees, turquoise waters in the distance, and a small propeller plane preparing to take off.',
    '(military base)1.2: A secure area with camouflaged aircraft, hangars, and soldiers in uniform, surrounded by fences and watchtowers.',
    '(jungle landing strip)1.2: A small, cleared area in the middle of dense jungle vegetation, with a light aircraft parked on the grass strip.',
    '(polar research station)1.2: A small airstrip surrounded by snow and ice, with a research aircraft parked next to a few prefabricated buildings and scientific equipment.',
    '(seaplane dock)1.2: A calm, clear body of water with a floating dock, where a seaplane is tied up, ready for its next flight.',
    '(cargo airport)1.2: A large expanse of concrete with cargo planes being loaded by forklifts, crates and containers stacked nearby, and airport staff in high-visibility vests.',
    '(arctic tundra landing strip)1.2: A barren, icy landscape with a small aircraft parked on a gravel runway, surrounded by frozen ground and distant mountains.',
    '(forest clearing airstrip)1.2: A small, grassy airstrip cut into a dense forest, with trees on either side and a single aircraft parked at the edge of the clearing.',
    '(volcanic island airstrip)1.2: A short runway on a remote island, with black volcanic rock surrounding the strip and an active volcano smoking in the distance.',
    '(desert oasis airstrip)1.2: A tiny airstrip near a lush oasis in the middle of an arid desert, with palm trees and a small pool of water visible in the background.',
    '(savannah airstrip)1.2: A dusty runway in the middle of the savannah, surrounded by tall grasses and scattered acacia trees, with wildlife visible in the distance.',
    '(small island airstrip)1.2: A short runway on a remote island, surrounded by a calm blue ocean, with waves gently lapping against the shore.',
    '(countryside glider field)1.2: A grassy field with gentle hills in the background, dotted with gliders and a plane waiting for tow-off.',
    '(valley airstrip)1.2: A narrow runway nestled between high cliffs, with a river flowing nearby and a plane preparing for takeoff.',
    '(aerial sky)1.2: A vast expanse of blue with soft clouds scattered, distant horizon blending with the sky, and the sun illuminating everything.',
    ],
    'cars':
    [
    '(city street)1.2: A bustling urban road filled with buildings, traffic lights, and pedestrians moving in every direction.',
    '(highway)1.2: A wide, multi-lane road stretching out for miles with cars speeding by and overhead signs directing traffic.',
    '(rural road)1.2: A narrow, winding road cutting through fields of tall grass and wildflowers, with the occasional farmhouse in the distance.',
    '(parking lot)1.2: A flat, expansive area lined with parking spaces and surrounded by commercial buildings and streetlights.',
    '(mountain pass)1.2: A steep, narrow road that winds through towering peaks with sharp curves and cliffs overlooking valleys below.',
    '(coastal road)1.2: A scenic route along the coastline, with the blue ocean on one side and cliffs or beaches on the other.',
    '(suburban neighborhood)1.2: A quiet street lined with houses, trees, and neatly trimmed lawns, with the occasional driveway and parked car.',
    '(desert highway)1.2: A long, empty road stretching through vast, arid desert landscapes, surrounded by sand dunes and cacti.',
    '(snowy road)1.2: A narrow path covered in snow and ice, with tall pine trees flanking either side and a car making its way cautiously through.',
    '(tunnel)1.2: A dark, concrete passage beneath the earth or through a mountain, with headlights illuminating the way.',
    '(forest road)1.2: A dirt or gravel path winding through dense trees and undergrowth, with sunlight filtering through the canopy above.',
    '(bridge)1.2: A large, elevated structure spanning a river or valley, with cars crossing high above the ground.',
    '(rainy street)1.2: A wet city road with reflections of neon signs and headlights shimmering on the pavement, as raindrops fall steadily.',
    '(country road)1.2: A two-lane road stretching through open fields, with grazing animals in the distance and an old barn along the way.',
    '(shopping mall parking)1.2: A large, crowded parking area filled with cars and people moving between the stores and their vehicles.',
    '(off-road trail)1.2: A rough, uneven path through rugged terrain with rocks, mud, and dense vegetation surrounding the way.',
    '(industrial area)1.2: A zone filled with warehouses, factories, and heavy vehicles, with trucks and cars moving between loading docks.',
    '(freeway interchange)1.2: A massive network of looping, elevated roads where cars navigate between different highways.',
    '(truck stop)1.2: A rest area along a highway with gas pumps, a convenience store, and rows of large trucks and cars parked for a break.',
    '(winter mountain road)1.2: A steep, icy road winding through snow-covered mountains with snowbanks piled on either side.',
    '(farmland)1.2: A dirt road cutting through fields of crops, with tractors in the distance and the smell of fresh earth in the air.',
    '(urban alley)1.2: A narrow, dimly lit alley between tall buildings, with a few cars parked along the sides and graffiti on the walls.',
    '(forest clearing)1.2: A grassy, open area in the middle of a dense forest, with a dirt path where cars can be seen parked or moving through.',
    '(beach parking lot)1.2: A sandy parking area near the coast, with cars lined up and the sound of waves crashing in the distance.',
    '(vineyard)1.2: A scenic area with rows of grapevines, with a small dirt road leading through the vineyard and a few cars parked nearby.',
    '(amusement park lot)1.2: A large, crowded parking area outside a theme park, with rides and attractions visible in the background.',
    '(residential driveway)1.2: A paved, sloping driveway leading to a suburban house, with a car parked near the garage or curb.',
    '(farmstead)1.2: A gravel road winding through a working farm, with barns, livestock, and tractors in view as cars pass by.',
    '(urban plaza)1.2: A bustling city square with people, outdoor cafes, and pigeons fluttering about.',
    ],
}

INFEASIBLE_BACK = {
    'oxford_pets':
    [
    "(space station)1.2: A high-tech interior with floating objects, control panels, and a view of Earth through a window.",
    "(deep sea)1.2: A dark, underwater environment with bioluminescent creatures and no sunlight.",
    "(volcano interior)1.2: A fiery landscape with flowing lava, molten rocks, and intense heat.",
    "(airplane cockpit)1.2: A confined space with numerous controls, screens, and a view of the sky through the windshield.",
    "(submarine interior)1.2: A cramped, metallic space with control panels, periscopes, and no natural light.",
    "(arctic ice floe)1.2: A vast, frozen landscape with floating ice sheets, frigid temperatures, and polar bears.",
    "(lava field)1.2: A barren, rocky expanse with hardened lava and occasional steam vents.",
    "(oil rig platform)1.2: A large, industrial platform in the ocean with heavy machinery and no land nearby.",
    "(active construction site)1.2: A noisy, chaotic area with heavy machinery, construction materials, and workers in hard hats.",
    "(satellite in orbit)1.2: The cold, empty expanse of space with Earth visible in the distance and no gravity.",
    "(cruise ship engine room)1.2: A noisy, mechanical room with large engines, pipes, and no windows.",
    "(crater of an active volcano)1.2: A dangerous environment with smoke, ash, and flowing lava.",
    "(bottom of the ocean)1.2: A pitch-black, high-pressure environment with strange deep-sea creatures and no light.",
    "(mars surface)1.2: A barren, reddish landscape with rocks, dust, and no signs of life.",
    "(hospital operating room)1.2: A sterile, brightly-lit room with surgical instruments, operating tables, and medical staff.",
    "(freezing tundra)1.2: A frozen, treeless landscape with harsh winds, snow, and subzero temperatures.",
    "(space shuttle cargo bay)1.2: An expansive, empty space with metallic walls and equipment secured to the sides.",
    "(active war zone)1.2: A dangerous area with explosions, damaged buildings, and soldiers in combat gear.",
    "(server farm)1.2: A large room filled with rows of servers, cooling systems, and blinking lights.",
    "(intense storm at sea)1.2: A chaotic scene with high waves, strong winds, and dark storm clouds.",
    "(deep space)1.2: The vast, empty expanse of space with distant stars, no gravity, and no solid ground.",
    "(tornado path)1.2: A chaotic environment with high winds, flying debris, and damaged structures.",
    "(sewer system)1.2: A dark, damp network of tunnels with flowing water, pipes, and an unpleasant smell.",
    "(chemical laboratory)1.2: A sterile environment with lab equipment, chemical storage, and safety warnings.",
    "(power plant control room)1.2: A room filled with monitors, control panels, and warning lights.",
    "(diamond mine)1.2: A dark, underground environment with narrow tunnels, mining equipment, and no natural light.",
    "(antarctic research station)1.2: A remote, icy landscape with scientific equipment, buildings, and extreme cold.",
    "(nuclear missile silo)1.2: A high-security area with missile silos, control panels, and heavy security measures.",
    "(underwater cave)1.2: A dark, submerged environment with stalactites, stalagmites, and no natural light.",
    "(industrial smelting plant)1.2: A hot, noisy environment with molten metal, large furnaces, and protective gear.",
    "(inside a hot air balloon)1.2: A confined space with a view of the sky, the burner, and the basket beneath.",
    "(antarctic ice shelf)1.2: A vast, frozen expanse with towering ice cliffs, frigid temperatures, and no vegetation.",
    "(active minefield)1.2: A dangerous area with warning signs, unexploded ordnance, and no safe paths.",
    "(industrial clean room)1.2: A sterile environment with air filtration systems, protective suits, and strict contamination controls.",
    "(atop a skyscraper)1.2: A high, open space with strong winds, a view of the city below, and no safety railings.",
    "(mountain peak)1.2: A rocky summit with sharp cliffs, snow-covered ridges, and a view of clouds below the peak.",
    "(car assembly line)1.2: A large industrial floor filled with moving mechanical arms, conveyor belts, and half-built vehicles being assembled in stages.",
    "(air traffic control tower)1.2: A tall, enclosed space with large windows providing a panoramic view of the airport runways and control panels.",
    "(inside a coal mine)1.2: A dark, underground tunnel with rough walls, wooden supports, and dust particles floating in the air.",
    "(train tracks)1.2: A set of steel rails running across gravel, surrounded by industrial buildings or open countryside, with distant train sounds.",
    "(deep cave)1.2: A dark, humid cavern with jagged rocks, dripping water, and the echo of footsteps, far from any light or warmth.",
    "(blue sky)1.2: A vast expanse of clear, cloudless blue sky, with nothing but the sun shining brightly in the distance.",
    '(deep space)1.2: The vast, empty expanse of space with distant stars, no gravity, and no solid ground.',
    "(moon surface)1.2: A barren, gray landscape filled with craters, dust, and no atmosphere.",
    "(black hole)1.2: A region of space where gravity is so strong that nothing, not even light, can escape.",
    "(saturn's rings)1.2: A vast expanse of ice and rock fragments orbiting the planet, with no solid ground or atmosphere.",
    "(sun's surface)1.2: A fiery expanse of plasma and intense radiation, with extreme temperatures that would incinerate anything in an instant.",
    "(asteroid belt)1.2: A chaotic region filled with floating rocks and debris, constantly moving and colliding.",
    "(jupiter's storm)1.2: A massive, swirling storm with violent winds and thick clouds of gas, offering no solid surface or breathable atmosphere.",
    "(inside a volcano)1.2: A scorching hot environment filled with flowing lava and toxic gases, with no road or safe space for vehicles.",
    ],

    'fgvc_aircraft':
            [
    '(underwater coral reef)1.2: A vibrant underwater scene filled with colorful corals, schools of fish, and shimmering light filtering through the water surface.',
    '(subterranean lava tube)1.2: A red-hot tunnel formed by flowing lava, with molten rock walls and glowing embers scattered across the floor.',
    '(crowded subway station)1.2: An underground platform filled with commuters waiting for a train, with tiled walls, metal tracks, and no open space for an aircraft.',
    '(cozy living room)1.2: A warm and inviting space with soft couches, a fireplace, bookshelves, and a coffee table, far too small and enclosed for any aircraft to fit.',
    '(art museum gallery)1.2: A large, elegant room filled with paintings and sculptures, with polished wooden floors and no indication of outdoor space.',
    '(library reading room)1.2: A quiet, well-lit room with rows of bookshelves, tables filled with reading materials, and people quietly reading or studying.',
    '(shopping mall interior)1.2: A bustling indoor space filled with stores, escalators, and shoppers, with no access to the sky or runway space.',
    '(dense city alley)1.2: A narrow, dimly lit alleyway between tall buildings, cluttered with trash bins, fire escapes, and little room to move.',
    '(high school classroom)1.2: A typical classroom setting with desks, a chalkboard, and students working on assignments, completely unsuited for an aircraft.',
    '(small home kitchen)1.2: A cozy kitchen with a stove, refrigerator, and dining table, where an aircraft would be far too large to fit.',
    '(artificial cave in an amusement park)1.2: A themed cave filled with artificial rocks, dim lighting, and winding paths meant for visitors, not large enough for an aircraft.',
    '(attic storage space)1.2: A dusty, cluttered attic filled with old furniture, boxes, and cobwebs, far too small and enclosed for an aircraft to fit.',
    '(train tunnel)1.2: A long, dark tunnel designed for trains, with tracks and narrow walkways along the sides, providing no room for an aircraft to pass through.',
    '(ice hotel)1.2: A beautifully sculpted room made entirely of ice, with frosty walls, ice beds, and low ceilings, located in a remote, frozen location.',
    '(cornfield)1.2: Tall rows of corn growing tightly together, creating a maze-like environment with no open space for an aircraft to land.',
    '(interior of a medieval castle)1.2: A stone-walled room with tapestries, wooden furniture, and narrow windows, completely unsuitable for modern aircraft.',
    '(underground cave system)1.2: A series of narrow tunnels and chambers deep beneath the earth, with stalactites and underground pools, completely inaccessible to aircraft.',
    '(opera house stage)1.2: A grand stage with red velvet curtains, ornate decorations, and seating for an audience, completely enclosed and unfit for aircraft.',
    '(construction site interior)1.2: An unfinished building with scaffolding, exposed beams, and construction equipment, not designed to accommodate an aircraft.',
    '(volcanic ash cloud)1.2: A swirling mass of ash and smoke spewing from an erupting volcano, with little to no visibility and extreme heat.',
    '(urban sewer tunnel)1.2: A narrow, dimly-lit underground tunnel with flowing water and concrete walls, filled with the echoing sound of dripping water.',
    '(subterranean cave)1.2: A naturally formed cave with stalactites, stalagmites, and narrow passageways, making it completely impractical for aircraft.',
    '(hospital emergency room)1.2: A sterile environment filled with doctors, patients, and medical equipment—an enclosed space not designed for any form of aircraft.',
    '(nuclear reactor core)1.2: A high-security environment filled with reactor equipment, radiation shielding, and control panels—unsuitable and dangerous for aircraft.',
    '(tight canyon pass)1.2: A narrow, twisting path between sheer rock walls—too risky and constrained for safe aircraft passage.',
    '(congested metropolitan plaza)1.2: A busy urban square filled with people, food stalls, and activities, offering no room for aircraft landing or navigation.',
    '(living room)1.2: A cozy space with a couch, a coffee table, and a dog bed near a window.',
    '(cafe)1.2: A cafe with outdoor seating, water bowls for dogs, and a few other patrons with their pets.',
    '(deep space)1.2: The vast, empty expanse of space with distant stars, no gravity, and no solid ground.',
    "(moon surface)1.2: A barren, gray landscape filled with craters, dust, and no atmosphere.",
    "(black hole)1.2: A region of space where gravity is so strong that nothing, not even light, can escape.",
    "(saturn's rings)1.2: A vast expanse of ice and rock fragments orbiting the planet, with no solid ground or atmosphere."
    "(sun's surface)1.2: A fiery expanse of plasma and intense radiation, with extreme temperatures that would incinerate anything in an instant.",
    "(asteroid belt)1.2: A chaotic region filled with floating rocks and debris, constantly moving and colliding.",
    "(jupiter's storm)1.2: A massive, swirling storm with violent winds and thick clouds of gas, offering no solid surface or breathable atmosphere.",
    "(inside a volcano)1.2: A scorching hot environment filled with flowing lava and toxic gases, with no road or safe space for vehicles.",
    "(chemical laboratory)1.2: A sterile environment with lab equipment, chemical storage, and safety warnings.",
    "(underwater cave)1.2: A dark, submerged environment with stalactites, stalagmites, and no natural light.",
    "(air traffic control tower)1.2: A tall, enclosed space with large windows providing a panoramic view of the airport runways and control panels.",
    "(school cafeteria)1.2: A large room filled with tables, chairs, and a food serving area, bustling with students and trays of food.",
    "(hospital waiting room)1.2: A quiet area with rows of chairs, magazines, and a reception desk, where patients wait for their appointments.",
    "(supermarket aisle)1.2: A long, narrow aisle lined with shelves stocked with groceries and shopping carts moving past.",
    "(gymnasium)1.2: A large hall with wooden floors, basketball hoops, and bleachers, often used for sports activities and events.",
    "(hotel lobby)1.2: A spacious entrance area with comfortable seating, a reception desk, and guests checking in or out.",
    "(library study room)1.2: A quiet space with individual desks, bookshelves, and students focused on their work.",
    "(office cubicle)1.2: A small, enclosed workspace with a desk, computer, and divider walls, designed for individual office tasks.",
    "(restaurant dining area)1.2: A cozy space filled with tables, chairs, and diners enjoying their meals, with waiters moving between the tables.",
    "(movie theater)1.2: A darkened room with rows of plush seats facing a large screen, where audiences watch films in silence.",
    '(suburban backyard)1.2: A grassy area with a wooden fence, a few trees, and a doghouse in one corner.',
    '(city park)1.2: A green space with open fields, walking paths, and other people walking their dogs.',
    '(living room)1.2: A cozy space with a couch, a coffee table, and a dog bed near a window.',
    ],
    'cars':
    [
    '(dense coral reef)1.2: A bright, underwater world filled with colorful corals, schools of fish, and no sign of roads or vehicles.',
    '(ocean surface)1.2: A vast, endless expanse of blue water with gentle waves and no solid ground to support a car.',
    '(volcanic crater)1.2: A barren, rocky landscape with flowing lava and toxic gases, impossible for any car to traverse.',
    '(cloud layer)1.2: A fluffy, white expanse in the sky where no ground exists, only clouds and open air.',
    '(glacier surface)1.2: A frozen, uneven expanse of solid ice, with deep crevasses and no place for a car to safely drive.',
    '(sea cave)1.2: A dark, enclosed space filled with water, echoing waves, and no room for a vehicle to enter or exit.',
    '(deep canyon floor)1.2: A narrow, rocky valley with steep cliffs towering above, with no road access or space for a car.',
    '(dense jungle floor)1.2: A thick underbrush filled with vines, roots, and fallen trees, with no clear path or solid ground.',
    '(underwater cave)1.2: A dark, submerged cave with stalactites, stalagmites, and no possibility for air-breathing vehicles.',
    '(mudslide slope)1.2: A steep hillside covered in flowing mud and debris, making it impossible for a car to stay in place.',
    '(iceberg)1.2: A floating mass of ice in the ocean, unstable and constantly shifting with no solid ground for a vehicle.',
    '(lava field)1.2: A hardened, uneven surface of cooled lava with sharp rocks and dangerous, unpredictable conditions.',
    '(dense kelp forest)1.2: An underwater environment filled with tall, swaying kelp plants, providing no solid surface for vehicles.',
    '(tidal wave)1.2: A massive, fast-moving wall of water surging toward the shore, where no vehicle could withstand the impact.',
    '(frozen lake)1.2: A sheet of ice covering a lake, which could crack under the weight of a car and send it plunging into freezing water.',
    '(deep ocean trench)1.2: A dark, deep underwater canyon with immense water pressure and no possibility for air-breathing vehicles.',
    '(tidal estuary)1.2: The mouth of a river where freshwater meets the sea, with constantly shifting tides and mudflats.',
    '(volcanic lava flow)1.2: A river of molten rock slowly flowing downhill, burning everything in its path and far too hot for a car.',
    '(floating iceberg field)1.2: A group of massive, unstable icebergs drifting through the ocean, constantly shifting and breaking apart.',
    '(volcano interior)1.2: A fiery landscape with flowing lava, molten rocks, and intense heat.',
    '(airplane cockpit)1.2: A confined space with numerous controls, screens, and a view of the sky through the windshield.',
    '(satellite in orbit)1.2: The cold, empty expanse of space with Earth visible in the distance and no gravity.',
    '(crater of an active volcano)1.2: A dangerous environment with smoke, ash, and flowing lava.',
    '(bottom of the ocean)1.2: A pitch-black, high-pressure environment with strange deep-sea creatures and no light.',
    '(mars surface)1.2: A barren, reddish landscape with rocks, dust, and no signs of life.',
    '(hospital operating room)1.2: A sterile, brightly-lit room with surgical instruments, operating tables, and medical staff.',
    '(space shuttle cargo bay)1.2: An expansive, empty space with metallic walls and equipment secured.',
    '(crowded subway station)1.2: An underground platform filled with commuters waiting for a train, with tiled walls, metal tracks, and no open space for a car.',
    '(cozy living room)1.2: A warm and inviting space with soft couches, a fireplace, bookshelves, and a coffee table, far too small and enclosed for any car to fit.',
    '(art museum gallery)1.2: A large, elegant room filled with paintings and sculptures, with polished wooden floors and no indication of outdoor space.',
    '(deep space)1.2: The vast, empty expanse of space with distant stars, no gravity, and no solid ground.',
    '(volcanic ash cloud)1.2: A swirling mass of ash and smoke spewing from an erupting volcano, with little to no visibility and extreme heat.',
    '(inside a hot air balloon)1.2: A confined space with a view of the sky, the burner, and the basket beneath, not designed for cars.',
    '(train tunnel)1.2: A dark, confined passage for trains, with tracks, dim lighting, and no space for a car to navigate safely.',
    '(living room)1.2: A cozy space with a couch, a coffee table, and a dog bed near a window.',
    '(deep space)1.2: The vast, empty expanse of space with distant stars, no gravity, and no solid ground.',
    "(moon surface)1.2: A barren, gray landscape filled with craters, dust, and no atmosphere.",
    "(black hole)1.2: A region of space where gravity is so strong that nothing, not even light, can escape.",
    "(saturn's rings)1.2: A vast expanse of ice and rock fragments orbiting the planet, with no solid ground or atmosphere.",
    "(sun's surface)1.2: A fiery expanse of plasma and intense radiation, with extreme temperatures that would incinerate anything in an instant.",
    "(asteroid belt)1.2: A chaotic region filled with floating rocks and debris, constantly moving and colliding.",
    "(jupiter's storm)1.2: A massive, swirling storm with violent winds and thick clouds of gas, offering no solid surface or breathable atmosphere.",
    "(inside a volcano)1.2: A scorching hot environment filled with flowing lava and toxic gases, with no road or safe space for vehicles.",
    "(school cafeteria)1.2: A large room filled with tables, chairs, and a food serving area, bustling with students and trays of food.",
    "(hospital waiting room)1.2: A quiet area with rows of chairs, magazines, and a reception desk, where patients wait for their appointments.",
    "(gymnasium)1.2: A large hall with wooden floors, basketball hoops, and bleachers, often used for sports activities and events.",
    "(office cubicle)1.2: A small, enclosed workspace with a desk, computer, and divider walls, designed for individual office tasks.",
    "(restaurant dining area)1.2: A cozy space filled with tables, chairs, and diners enjoying their meals, with waiters moving between the tables.",
    "(movie theater)1.2: A darkened room with rows of plush seats facing a large screen, where audiences watch films in silence.",
    ],
}
